[build]
  base = "" # si es necesario, especifica otra carpeta base (la mayoría de las veces, puedes dejarla vacía)
  publish = "dist/angular_proyect"
  command = "ng build --configuration production"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
