[build]
publish = "dist/angular_proyect/browser"
command = "ng build --configuration production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Comenta o elimina esta sección de Edge Functions
# [[edge_functions]]
# path = "netlify/edge-functions"
# function = "server-render"
